### ISSUE TITLE
Code review and suggested modifications 

### ISSUE THREAD

**Issue by gmuraleekrishna** [shireesha1990/ProgrammingChallenge#1]
Hi,

The code seems to be working fine, and you have given a decent README as well.

There are a bunch of code improvements to be taken care of

*  The code is not modular
* Part B of the problem is missing
* Method, file, and variable naming is to be taken seriously, Follow relevant conventions for the language

**Comment by shireesha1990** [comment]
Thank you Muralee Krishna for code review , I will do necessary changes  and send it.

**Comment by shireesha1990** [comment]
Hi ,

I have closed Part A issue #1. I am yet to complete Part B . I will require some more time.

**Comment by shireesha1990** [comment]
I have tried my level best to complete PartB. User can any add number of field value

Thank you
